name: Build and Deploy NGINX to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: venu-5198
  REGION: us-east1
  CLUSTER_NAME: fastapi-cluster
  GAR_REPO: gke-nginx-repo
  IMAGE: nginx

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # ✅ Authenticate to Google Cloud
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # ✅ Install Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    # ✅ Enable Docker auth for GAR
    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

    # ✅ Build and Push Docker Image
    - name: Build and Push Docker image
      run: |
        IMAGE_NAME=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO }}/${{ env.IMAGE }}:latest
        echo "Building image: $IMAGE_NAME"
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    # ✅ Install GKE Auth Plugin
    - name: Install GKE Auth Plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin --quiet

    # ✅ Connect to GKE cluster
    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} \
          --region ${{ env.REGION }} --project ${{ env.PROJECT_ID }}

    # ✅ Update image in deployment and apply YAMLs
    - name: Deploy to GKE
      run: |
        kubectl set image deployment/nginx-deployment nginx-container=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO }}/${{ env.IMAGE }}:latest --record || true
        kubectl apply -f k8s/ --validate=false
        kubectl get pods
        kubectl get svc
