name: Deploy NGINX to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: venu-5198
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials fastapi-cluster --region us-east1 --project venu-5198

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/
        kubectl get pods
        kubectl get svc

